import Sidebar from "@/components/shared/Sidebar";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 
    <div className="flex min-h-screen bg-slate-50 dark:bg-zinc-950 text-slate-900 dark:text-zinc-100">
   <Sidebar />
        {children}
</div>
       

  );
}
